/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 版本与最低客户端版本(客户端据此决定是否强制升级) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VersionInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前登录者(不含任何权限列表,R-13) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeView"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录(账密) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新令牌 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出(吊销当前刷新令牌) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已登出 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列目录(keyset 分页)
         * @description 参数名以本文档与架构文档为准:`space` / `parent`。
         *     服务端同时接受历史拼法 `space_id` / `parent_id`(同义别名),
         *     但**只声明一个规范名** —— 声明两个同义参数会让生成的客户端类型出现
         *     两个字段,调用方无从选择。
         */
        get: {
            parameters: {
                query?: {
                    space?: string;
                    parent?: string;
                    limit?: number;
                    /** @description 上一页最后一个条目的 lower(name) */
                    after?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FileListResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
                410: components["responses"]["SpaceRevoked"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/dirs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新建目录(Bearer 令牌可用的 REST 入口)
         * @description 目录创建此前**只有 WebDAV MKCOL** 一个入口(见 ADR-6:WebDAV 走 Basic
         *     账密换票)。桌面客户端按设计只持有 Bearer 令牌、没有账密,于是它
         *     **建不了目录** —— 连带"任何要放进子目录的文件"都传不上去
         *     (实测报错:`WebDAV 认证失败: 请提供 Basic 凭据`)。本路径补上这个缺口。
         *
         *     `space_id` / `parent_id` 缺省时分别落到**调用者的个人空间**与**该空间
         *     根目录**(与 `GET /api/v1/files` 的两个参数同义,含历史别名拼法)。
         *
         *     语义是**严格新建**:同目录下已有同名条目(不分大小写)→ 409
         *     `name_conflict`,**不**顺手返回已有条目 —— 想"复用已存在目录"的调用方
         *     自己按名字查一次;把两种意图塞进同一个 201 会让客户端无法区分
         *     "我刚建了它"与"它本来就存在",而这正是同步逻辑需要的区别。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 缺省 = 调用者个人空间 */
                        space_id?: string;
                        /** @description 缺省 = 空间根目录 */
                        parent_id?: string;
                        name: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntryView"];
                    };
                };
                400: components["responses"]["BadRequest"];
                409: components["responses"]["Conflict"];
                410: components["responses"]["SpaceRevoked"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 文件详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntryView"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** 硬删(无回收站;目录删整棵子树) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 同步完成(子树行数 ≤ dir_op_sync_max_rows) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteResult"];
                    };
                };
                /**
                 * @description 超阈值已转异步删除(6.11):行**此刻还在**,响应里只有 task_id。
                 *     轮询 `GET /api/v1/tasks/{id}`;入队后该子树上的读写一律 409
                 *     `dir_op_in_progress`,直到任务结束。
                 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteResult"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        options?: never;
        head?: never;
        /** 改名(带 base_version 乐观锁) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /**
                         * Format: int64
                         * @default 0
                         */
                        base_version?: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntryView"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        trace?: never;
    };
    "/api/v1/files/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 下载(流式;支持 Range/If-Range/条件请求) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 完整内容 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 部分内容 */
                206: {
                    headers: {
                        "Content-Range"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description ETag 未变 */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
                /** @description Range 越界 */
                416: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** 取内容元信息(与 GET 同头:ETag/Content-Length/Content-Type,不回 body) */
        head: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 头信息 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description ETag 未变 */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 移动(可同时改名;不跨空间) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        parent_id: string;
                        name?: string;
                        /**
                         * Format: int64
                         * @default 0
                         */
                        base_version?: number;
                    };
                };
            };
            responses: {
                /** @description 同步完成(子树行数 ≤ dir_op_sync_max_rows) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MoveResult"];
                    };
                };
                /**
                 * @description 超阈值已转异步任务(6.11):响应里只有 task_id,条目还在原位置。
                 *     客户端轮询 `GET /api/v1/tasks/{id}`,任务完成后再刷新列表 ——
                 *     **不要**在收到 202 时本地做乐观移动(任务可能失败)。
                 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MoveResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 目录级异步任务状态(6.11,供轮询)
         * @description 只返回**自己的**任务(管理员例外);非本人一律 404 而不是 403 ——
         *     403 等于确认"这个任务 id 存在",而任务里有空间/文件 id 与文件名。
         *     未结束时**不回** `rows_affected/freed_bytes/released_objects`
         *     (回 0 会被客户端当成"这次操作什么都没删")。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskStatus"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/subtree-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 子树影响面预检(删除确认与容量预估共用) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubtreeStats"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 复制文件或目录(逻辑复制 + 引用计数,不搬内容) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        target_parent_id?: string;
                        /** @description 空则自动生成"原名 (副本)" */
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CopyResult"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/share-to-space": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 共享到另一个空间(只新建元数据行 + 引用 +1) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        target_space_id: string;
                        target_parent_id?: string;
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntryView"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 查询编辑锁(不含持有者身份以外的信息;无锁时 404) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            lock?: components["schemas"]["LockView"];
                            /** Format: int64 */
                            ttl_seconds?: number;
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** 获取/续期编辑锁(30min;过期可抢占) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            lock?: components["schemas"]["LockView"];
                            /** Format: int64 */
                            ttl_seconds?: number;
                        };
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        /** 释放编辑锁(幂等) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已释放 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建上传任务(预留额度;预检命中时下发秒传挑战) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UploadCreateRequest"];
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadCreateResult"];
                    };
                };
                409: components["responses"]["Conflict"];
                507: components["responses"]["QuotaExceeded"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 取消上传(即时释放预留) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已取消 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        /** 取当前偏移(断点续传) */
        head: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        "Upload-Offset"?: number;
                        "Upload-Length"?: number;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 秒传定稿(免重传;证明未过 → 403 fast_upload_denied) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nonce: string;
                        sample_sha256: string[];
                    };
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadSimpleResult"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 增量变更流(超窗 → 409 cursor_expired → 全量清单) */
        get: {
            parameters: {
                query: {
                    space: string;
                    since?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChangesPage"];
                    };
                };
                409: components["responses"]["Conflict"];
                410: components["responses"]["SpaceRevoked"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/changes/head": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前最大 change_seq(首次同步的增量起点) */
        get: {
            parameters: {
                query: {
                    space: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            space_id?: string;
                            /** Format: int64 */
                            head_seq?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/cursors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上报游标(单维取 max;全局水位取 min) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        client_id: string;
                        space_id: string;
                        /** Format: int64 */
                        last_seq: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我创建的分享 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            shares?: components["schemas"]["ShareItem"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 创建分享链接(唯一免登录出口) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        file_id: string;
                        password?: string;
                        expires_in_hours?: number;
                        max_downloads?: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShareCreated"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shares/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 吊销分享(幂等) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已吊销 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shares/{token}/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 落地页免登录查询(不回下载地址) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShareMeta"];
                    };
                };
                404: components["responses"]["NotFound"];
                410: components["responses"]["Gone"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shares/{token}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 免登录下载(校验 token + 密码;计入下载次数) */
        get: {
            parameters: {
                query?: {
                    password?: string;
                };
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 内容 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                410: components["responses"]["Gone"];
            };
        };
        put?: never;
        /** 免登录下载(POST 形态,密码走 body 或 query) */
        post: {
            parameters: {
                query?: {
                    password?: string;
                };
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 内容 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                410: components["responses"]["Gone"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 部门树(闭包表) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DepartmentNode"][];
                    };
                };
            };
        };
        put?: never;
        /** 新建部门 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        parent_id?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/departments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除部门 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我能看到的空间(服务端按权限过滤;协作界面第一屏) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpaceList"];
                    };
                };
            };
        };
        put?: never;
        /** 创建团队空间(一次事务里建 组 + 空间 + 根目录 + owner 的 manager 成员) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            responses: {
                /** @description 已创建 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpaceView"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 解散团队空间(仅 owner;**硬删**,4.5 无回收站)
         * @description 空间内必须已清空(除根目录外无条目),否则 409 并给出还需清掉的条目数。
         *     硬删意味着 UI 必须二次确认(前端的解散要求手输空间名)。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已解散 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            dissolved?: boolean;
                            id?: string;
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                410: components["responses"]["SpaceRevoked"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 转让空间所有权(仅 owner;按用户名或 id 指定新 owner) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        new_owner_id?: string;
                        /** @description 协作界面里人能输入的只有用户名,故服务端直接解析(见 resolveUser) */
                        new_owner_username?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: string;
                            new_owner_id?: string;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 成员列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemberList"];
                    };
                };
                410: components["responses"]["SpaceRevoked"];
            };
        };
        /** 新增或改权限(幂等;H5 与桌面端统一用 PUT) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        user_id?: string;
                        username?: string;
                        permission?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemberView"];
                    };
                };
            };
        };
        /** 邀请成员(与 PUT 同语义;按用户名或 id) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        user_id?: string;
                        username?: string;
                        /** @description manager / editor / reader */
                        permission?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemberView"];
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 移除成员(即时生效:下一个请求就被拒,不等 JWT 过期) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已移除 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{id}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 主动退出(owner 退出前必须转让 → 409) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已退出 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 你是所有者,必须先转让(否则空间会失去所有者) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/spaces/{id}/freeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 冻结/解冻空间 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        frozen?: boolean;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            request_id?: string;
        };
        VersionInfo: {
            version: string;
            min_client_version?: string;
            api_contract?: string;
        };
        MeView: {
            user_id: string;
            username: string;
            role: string;
            audience: string;
            request_id?: string;
        };
        LoginRequest: {
            login: string;
            password: string;
            /**
             * @description 分端受众(R-14):web / h5 / desktop
             * @enum {string}
             */
            audience?: "web" | "h5" | "desktop";
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
            token_type: string;
            /** Format: int64 */
            expires_in: number;
            audience: string;
        };
        LoginResult: {
            token: components["schemas"]["TokenPair"];
            user: components["schemas"]["UserBrief"];
            personal_space?: components["schemas"]["SpaceBrief"];
        };
        UserBrief: {
            id: string;
            username: string;
            role: string;
            display_name?: string;
        };
        SpaceBrief: {
            id: string;
            name: string;
        };
        SpaceView: {
            id: string;
            /** @description personal / team */
            kind: string;
            name: string;
            owner_id: string;
            /** Format: int64 */
            quota_bytes?: number;
            /** Format: int64 */
            used_bytes?: number;
            frozen?: boolean;
            /** @description 仅供展示(客户端不得据此决定是否发请求;判权只在服务端) */
            is_owner?: boolean;
        };
        MemberView: {
            user_id: string;
            username?: string;
            display_name?: string;
            /** @description manager / editor / reader */
            permission: string;
        };
        SpaceList: {
            spaces: components["schemas"]["SpaceView"][];
            total: number;
        };
        MemberList: {
            members: components["schemas"]["MemberView"][];
            total: number;
        };
        /** @description 文件/目录条目(6.4:必须带 version/etag/size/updated_at/mime) */
        EntryView: {
            id: string;
            space_id?: string;
            parent_id?: string;
            name: string;
            is_dir: boolean;
            /** Format: int64 */
            size: number;
            mime_type?: string;
            hash_sha256?: string;
            /** Format: int64 */
            version: number;
            /** @description 已加引号的强 ETag(全项目唯一出口 quoteETag) */
            etag: string;
            depth?: number;
            updated_at: string;
            created_at?: string;
        };
        FileListResult: {
            space_id: string;
            parent_id: string;
            entries: components["schemas"]["EntryView"][];
            /** @description 非空表示还有下一页,原样回传即可 */
            next_after?: string;
        };
        DeleteResult: {
            /** Format: int64 */
            deleted_files: number;
            /** Format: int64 */
            deleted_dirs: number;
            /**
             * Format: int64
             * @description 因引用归零而转入延迟删除的对象数(回收的物理对象数)
             */
            released_objects: number;
            /**
             * Format: int64
             * @description 子树内不同物理对象的个数(与 subtree-stats 的 object_refs 同口径)
             */
            distinct_objects?: number;
            /** Format: int64 */
            freed_bytes: number;
            /** @description 非空 = 已转异步(6.11);此刻上面那些计数都是 0,真正结果去 /tasks/{id} 取 */
            task_id?: string;
            async: boolean;
        };
        /**
         * @description 移动的结果。同步完成时 `entry` 非空;超阈值转异步时只有 `task_id` ——
         *     刻意用**同一个结构体**而不是两个接口:客户端只需判断 `async` 一个字段,
         *     不必为"大目录"单独写一条调用路径。
         */
        MoveResult: {
            entry?: components["schemas"]["EntryView"];
            task_id?: string;
            /** @description true = 超阈值已转异步任务,客户端轮询 /api/v1/tasks/{id} */
            async: boolean;
        };
        TaskStatus: {
            id: string;
            /** @enum {string} */
            kind: "move" | "delete";
            /** @enum {string} */
            state: "pending" | "running" | "done" | "failed";
            /** @description 子树根(delete 完成后该行已不存在) */
            file_id: string;
            space_id: string;
            /** @description 恒为 true(轮询接口不存在同步语义) */
            async: boolean;
            name?: string;
            is_dir?: boolean;
            /**
             * Format: int64
             * @description 仅结束时返回
             */
            rows_affected?: number;
            /**
             * Format: int64
             * @description 仅结束时返回
             */
            freed_bytes?: number;
            /**
             * Format: int64
             * @description 仅结束时返回
             */
            released_objects?: number;
            /** @description 失败的稳定业务码(客户端按码分流) */
            error_code?: string;
            error_message?: string;
            created_at: string;
            finished_at?: string;
        };
        SubtreeStats: {
            file_id: string;
            name?: string;
            is_dir: boolean;
            /** Format: int64 */
            file_count: number;
            /** Format: int64 */
            dir_count: number;
            /** Format: int64 */
            total_size_bytes: number;
            /** Format: int64 */
            object_refs: number;
            /** Format: int64 */
            dedup_saved_bytes: number;
        };
        CopyResult: {
            root?: components["schemas"]["EntryView"];
            /** Format: int64 */
            copied_files: number;
            /** Format: int64 */
            copied_dirs: number;
            /** Format: int64 */
            object_refs_added: number;
            /** Format: int64 */
            size_bytes: number;
        };
        LockView: {
            file_id: string;
            holder_user_id: string;
            mine: boolean;
            expires_at: string;
        };
        UploadCreateRequest: {
            space_id?: string;
            parent_id?: string;
            name: string;
            /** Format: int64 */
            size: number;
            /**
             * @description 显式声明"这次上传要**覆盖**同目录同名文件"(默认 false = 同名直接 409 name_conflict)。
             *     为什么必须显式:默认允许覆盖时,两个客户端同时向同名位置上传不同内容,后到者会
             *     **静默覆盖**先到者 —— 用户看到"文件传上去了,内容却变了"(6.7 禁止静默覆盖)。
             *     客户端只有在**自己已经判定过**"这是我的改动、且远端版本没有比我知道的更新"时
             *     才该置 true;覆盖会让该 files 行的 version **原地 +1**(而不是新建一行)。
             * @default false
             */
            allow_overwrite: boolean;
            /** @description 客户端声明的 SHA-256(仅用于秒传预检,服务端定稿时重算) */
            hash?: string;
        };
        /** @description 预检命中的持物证明挑战(提示而非许可;挑战没过就要全量上传) */
        FastUploadHint: {
            nonce: string;
            /** Format: int64 */
            sample_len: number;
            sample_offsets: number[];
            /** Format: int64 */
            expires_in_seconds: number;
        };
        UploadCreateResult: {
            upload_id: string;
            /** @description 只在创建时返回一次(库内只存 SHA-256) */
            upload_ticket: string;
            expires_at: string;
            space_id: string;
            parent_id: string;
            name: string;
            /** Format: int64 */
            quota_after_bytes?: number;
            fast_upload?: components["schemas"]["FastUploadHint"];
        };
        UploadSimpleResult: {
            file: components["schemas"]["EntryView"];
            upload_id: string;
            deduped: boolean;
            new_file: boolean;
            /** Format: int64 */
            quota_after?: number;
            /** @description 幂等重放(同一 upload 已定稿,直接回既有结果) */
            replayed?: boolean;
        };
        ChangeItem: {
            /** Format: int64 */
            change_seq: number;
            file_id: string;
            /** @enum {string} */
            kind: "created" | "updated" | "moved" | "deleted" | "shared_in";
            /** Format: int64 */
            version: number;
            parent_id: string;
            name?: string;
            /** @description 仅 moved 有值 */
            old_parent_id?: string;
        };
        ChangesPage: {
            items: components["schemas"]["ChangeItem"][];
            /** Format: int64 */
            next_seq: number;
            has_more: boolean;
            space_id: string;
        };
        ShareMeta: {
            token: string;
            name: string;
            /** Format: int64 */
            size: number;
            is_dir: boolean;
            need_password: boolean;
            expires_at?: string;
            download_count?: number;
            max_downloads?: number;
            mime_type?: string;
        };
        ShareCreated: {
            id: string;
            token: string;
            file_id: string;
            need_password: boolean;
            expires_at?: string;
            max_downloads?: number;
            download_count?: number;
            path?: string;
        };
        ShareItem: {
            id: string;
            token: string;
            file_id: string;
            need_password: boolean;
            expires_at?: string;
            revoked: boolean;
            download_count: number;
            max_downloads?: number;
            name?: string;
            /** Format: int64 */
            size?: number;
            is_dir?: boolean;
        };
        DepartmentNode: {
            id: string;
            name: string;
            parent_id?: string;
            children?: components["schemas"]["DepartmentNode"][];
        };
    };
    responses: {
        /** @description 参数非法 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 未认证/令牌无效(need_password=true 表示分享需要密码) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 无权限(含 fast_upload_denied / 锁被他人持有) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description 冲突(版本/重名/游标超窗/空间已满/目录任务进行中)。
         *     `details.reason` 的可取值:version_conflict / name_conflict /
         *     target_is_directory / root_protected / **dir_op_in_progress**
         *     (后者表示该子树正在跑异步目录任务,客户端应提示"稍后再试"并刷新,
         *     而不是重试 —— 重试必然还是 409,直到任务结束)。
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 曾经存在、现在不可用(410:空间被移出/分享失效) */
        Gone: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 空间被移出或解散(410;客户端必须保留本地数据) */
        SpaceRevoked: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 额度不足(507;storage_full 表示服务端磁盘水位) */
        QuotaExceeded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 被限速(带 Retry-After) */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
